#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

# CORE MODULES:
use Encode;
use File::Spec::Functions qw(catdir);

# CPAN MODULES:
use JSON::PP;
use Mojolicious::Lite;

# CUSTOM APPLICATION PATHS:
my $resources_folder = catdir($ENV{PWD}, 'resources');
my $app_folder = catdir($resources_folder, 'app');
my $data_folder = catdir($resources_folder, 'data');

# Templates path:
unshift @{app->renderer->paths}, $app_folder;
# Static files path:
unshift @{app->static->paths}, $app_folder;

# GET JSON DATA FROM EXTERNAL FILE:
my $file = catdir($data_folder, 'questions.json');
my $raw_json_data;
{
  open my $filehandle, '<', $file or die;
  local $/ = undef;
  $raw_json_data = <$filehandle>;
  close $filehandle;
}

my $json_object = new JSON::PP;
my $questions_object =
  $json_object->JSON::PP::decode(Encode::encode('UTF-8', $raw_json_data));

my @questions = @{$questions_object->{'questions'}};

# ROUTE HANDLER:
get '/' => sub {
  my $page_handler = shift;
  $page_handler->render('index');
};

get '/get_question' => sub {
  my $page_handler = shift;
  my $question_number = $page_handler->param('number');

  my %response_hash = (
    "question" => Encode::decode('UTF-8', $questions[$question_number]->{"question"}),
    "class" => Encode::decode('UTF-8', $questions[$question_number]->{"class"}),
    "a" => Encode::decode('UTF-8', $questions[$question_number]->{"variants"}->{"a"}),
    "b" => Encode::decode('UTF-8', $questions[$question_number]->{"variants"}->{"b"}),
    "c" => Encode::decode('UTF-8', $questions[$question_number]->{"variants"}->{"c"}),
    "d" => Encode::decode('UTF-8', $questions[$question_number]->{"variants"}->{"d"}),
  );

  my $response_json = encode_json \%response_hash;
  $page_handler->render(
    text => Encode::decode('UTF-8', $response_json),
    status => 200, format => 'json'
  );
};

get '/check_answer' => sub {
  my $page_handler = shift;
  my $question_number = $page_handler->param('number');

  my %response_hash = (
    "answer" => Encode::decode('UTF-8', $questions[$question_number]->{"answer"}),
  );

  my $response_json = encode_json \%response_hash;
  $page_handler->render(
    text => Encode::decode('UTF-8', $response_json),
    status => 200, format => 'json'
  );
};

# SERVER STARTER:
app->start;
